"""add pet profile data field in pet model and update allergi model

Revision ID: 0215e956bcef
Revises: 5bb0f3340fc4
Create Date: 2025-07-24 14:24:12.391601

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '0215e956bcef'
down_revision = '5bb0f3340fc4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('allergi', sa.Column('detail', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=True))
    op.add_column('pet', sa.Column('favorite_food', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True))
    op.add_column('pet', sa.Column('favorite_toy', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True))
    op.add_column('pet', sa.Column('favorite_activity', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=True))
    op.add_column('pet', sa.Column('aggresive', sa.Boolean(), nullable=True))
    op.add_column('pet', sa.Column('pulls', sa.Boolean(), nullable=True))
    op.add_column('pet', sa.Column('strangers', sa.Boolean(), nullable=True))
    op.add_column('pet', sa.Column('walk_time', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=True))
    op.add_column('pet', sa.Column('feeding_time', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=True))
    op.add_column('pet', sa.Column('evening_routine', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('pet', 'evening_routine')
    op.drop_column('pet', 'feeding_time')
    op.drop_column('pet', 'walk_time')
    op.drop_column('pet', 'strangers')
    op.drop_column('pet', 'pulls')
    op.drop_column('pet', 'aggresive')
    op.drop_column('pet', 'favorite_activity')
    op.drop_column('pet', 'favorite_toy')
    op.drop_column('pet', 'favorite_food')
    op.drop_column('allergi', 'detail')
    # ### end Alembic commands ###
