"""remove bio from user and add bio into pet

Revision ID: 181ef8f44403
Revises: 675a09f59c80
Create Date: 2025-07-24 16:48:58.737081

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '181ef8f44403'
down_revision = '675a09f59c80'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pet', sa.Column('bio', sqlmodel.sql.sqltypes.AutoString(length=65535), nullable=True))
    op.drop_column('user', 'bio')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('bio', sa.VARCHAR(length=65535), autoincrement=False, nullable=True))
    op.drop_column('pet', 'bio')
    # ### end Alembic commands ###
