"""add chipnumber field into pet model

Revision ID: 227a21a8c17d
Revises: 91e8f404dd61
Create Date: 2025-07-24 08:05:42.035067

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '227a21a8c17d'
down_revision = '91e8f404dd61'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pet', sa.Column('chipnumber', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('pet', 'chipnumber')
    # ### end Alembic commands ###
