"""Initial migration

Revision ID: 2f81b4701077
Revises: 
Create Date: 2025-07-21 02:16:07.671577

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '2f81b4701077'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('email', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('phone_number', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=True),
    sa.Column('address', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=True),
    sa.Column('password', sqlmodel.sql.sqltypes.AutoString(length=128), nullable=False),
    sa.Column('hashed_password', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('language', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=True),
    sa.Column('notification', sa.Boolean(), nullable=False),
    sa.Column('membership', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=True)
    op.create_index(op.f('ix_user_id'), 'user', ['id'], unique=False)
    op.create_table('pet',
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('type', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=True),
    sa.Column('gender', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=True),
    sa.Column('age', sa.Integer(), nullable=True),
    sa.Column('breed', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('weight', sa.Float(), nullable=True),
    sa.Column('allergi', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=True),
    sa.Column('vaccination', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=True),
    sa.Column('color', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=True),
    sa.Column('height', sa.Float(), nullable=True),
    sa.Column('relationship', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=True),
    sa.Column('avatar', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('pet')
    op.drop_index(op.f('ix_user_id'), table_name='user')
    op.drop_index(op.f('ix_user_email'), table_name='user')
    op.drop_table('user')
    # ### end Alembic commands ###
