"""update last version

Revision ID: 675a09f59c80
Revises: 0215e956bcef
Create Date: 2025-07-24 15:59:34.105748

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '675a09f59c80'
down_revision = '0215e956bcef'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
