"""update pet schema

Revision ID: 767f6b507731
Revises: eb1e63f6e34f
Create Date: 2025-08-03 23:28:06.838439

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '767f6b507731'
down_revision = 'eb1e63f6e34f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
