"""add bio field to user model

Revision ID: 91e8f404dd61
Revises: 2f81b4701077
Create Date: 2025-07-24 06:58:08.639518

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '91e8f404dd61'
down_revision = '2f81b4701077'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('bio', sqlmodel.sql.sqltypes.AutoString(length=65535), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'bio')
    # ### end Alembic commands ###
