"""Add Insurance model

Revision ID: b3aa728bf2df
Revises: 227a21a8c17d
Create Date: 2025-07-24 08:25:17.100563

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = 'b3aa728bf2df'
down_revision = '227a21a8c17d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('insurance',
    sa.Column('provider', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('policy', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('coverage', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=True),
    sa.Column('deductible', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=True),
    sa.Column('reimbursement', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=True),
    sa.Column('expires', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=True),
    sa.Column('emergency_hotline', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=True),
    sa.Column('notes', sqlmodel.sql.sqltypes.AutoString(length=65535), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('pet_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['pet_id'], ['pet.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('insurance')
    # ### end Alembic commands ###
